logging:
  config: classpath:log4j2.xml

server:
  port: 10086
  servlet:
    context-path: /mybatis-starter
spring:
  datasource:
    # MYSQL
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/STUDENT_MANAGEMENT?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    #url: jdbc:mysql://localhost:3306/MS_TEST?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    #username: root
    #password: "Love888*+"
    # ORACLE
    #driver-class-name: oracle.jdbc.OracleDriver
    #url: jdbc:oracle:thin:@192.168.61.111:1521:orcl
    #username: flfwsjzx
    #password: flfwsjzx
    # SQL SERVER
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #url: jdbc:sqlserver://172.16.171.129:1433;databaseName=MySchool
    #username: sa
    #password: "Love888*+"
    # postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/MySchool
    username: postgres
    password: "Love888*+"
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 8
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 300000
      #connection-test-query: SELECT 1
lost:
  mybatis:
    #mapper-locations:
      #- classpath:/mybatis/mapper/*.xml
    configuration:
      call-setters-on-nulls: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      #map-underscore-to-camel-case: false
    custom-configuration:
      identity: false
      worker: true
      #dialect: mysql
      jdbc-type-auto-mapping: true
      dialect: postgresql

